Create logfile_dpkg if it doesn't exist
The reading of logfile_dpkg will crash if the file doesn't exist e.g.:

bdmurray@clean-xenial-amd64:~$ sudo /usr/bin/unattended-upgrade
Traceback (most recent call last):
  File "/usr/bin/unattended-upgrade", line 1468, in <module>
    main(options)
  File "/usr/bin/unattended-upgrade", line 1406, in main
    log_content = get_dpkg_log_content(logfile_dpkg, install_start_time)
  File "/usr/bin/unattended-upgrade", line 1075, in get_dpkg_log_content
    with io.open(logfile_dpkg, encoding='utf-8') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/var/log/unattended-upgrades/unattended-upgrades-dpkg.log'

I figured creating it right away was better than checking for the file existence in get_dpkg_log_content and encountering a crash somewhere else.  This fixes Launchpad bug 1590321.