Load modules lazily loaded by datetime.datetime.strptime() when u-u starts
When Python is upgraded to a new major version the the version running
unattended-upgrades can be removed as being newly unused causing a crash with:
ModuleNotFoundError: No module named '_strptime'.

To work around the issue load _strptime in advance by calling
datetime.datetime.strptime() early.